spring:
  application:
    name: MoneyCoach

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver

# Активный профиль задаётся через JVM-параметр:
# -Dspring.profiles.active=prod или test

# OpenAPI / Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: false
